name: Auto Commit

on:
  schedule:
    - cron: '30 0 * * *'  # Runs every day at 6 AM UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "ahhmeddd-11"
          git config user.email "syedahmed4957@gmail.com"

      - name: Make a dummy change
        run: |
          date >> update.log
          git add -f update.log
          git commit -m "🌱 Daily commit - keep green!"
          git push origin
